include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  
  errors:
    invalid_annotation_target: ignore
  
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # Error Rules
    avoid_dynamic_calls: true
    avoid_empty_else: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    cancel_subscriptions: true
    close_sinks: true
    
    # Style Rules
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    always_use_package_imports: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_catching_errors: true
    avoid_classes_with_only_static_members: true
    avoid_private_typedef_functions: true
    avoid_redundant_argument_values: true
    avoid_renaming_method_parameters: true
    avoid_returning_null_for_void: true
    avoid_single_cascade_in_expression_statements: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    
    # Pub Rules
    depend_on_referenced_packages: true
    package_names: true
    
    # Documentation
    comment_references: true
    
    # Formatting
    directives_ordering: true
    lines_longer_than_80_chars: false
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    require_trailing_commas: true
    sort_child_properties_last: true
    sort_constructors_first: true
    unnecessary_await_in_return: true
    unnecessary_parenthesis: true
    use_decorated_box: true
    use_super_parameters: true